// pages/GenerateTips.jsx

import { useState } from 'react';
import { generateTip, saveTip } from '../services/tipService.js';
import '../styles/tips.css';
import '../styles/auth.css';

const GenerateTips = () => {
  const [form, setForm] = useState({ subject: '', education_level: 'university' });
  const [result, setResult] = useState(null);
  const [loading, setLoading] = useState(false);
  const [saving, setSaving] = useState(false);
  const [error, setError] = useState('');
  const [saved, setSaved] = useState(false);

  const handleChange = (e) => {
    setError('');
    setForm((prev) => ({ ...prev, [e.target.name]: e.target.value }));
  };

  const handleGenerate = async (e) => {
    e.preventDefault();
    if (!form.subject.trim()) { setError('Please enter a subject.'); return; }
    setLoading(true);
    setError('');
    setResult(null);
    setSaved(false);
    try {
      const res = await generateTip(form);
      setResult(res.data);
    } catch (err) {
      setError(err.response?.data?.message || 'Generation failed. Please try again.');
    } finally {
      setLoading(false);
    }
  };

  const handleSave = async () => {
    if (!result) return;
    setSaving(true);
    try {
      await saveTip({
        persona_key: result.persona_key,
        subject: result.subject,
        education_level: result.education_level,
        title: result.title,
        content: result.content,
      });
      setSaved(true);
    } catch (err) {
      setError(err.response?.data?.message || 'Failed to save tip.');
    } finally {
      setSaving(false);
    }
  };

  const buildEmailBody = () => {
    if (!result) return '';
    return encodeURIComponent(
      `Study Tips: ${result.title}\n\n${result.content}\n\n— Generated by AcadeMe`
    );
  };

  return (
    <main className="generate-container">
      <h1>Generate Study Tips</h1>
      <p className="subtitle">
        Enter a subject and your education level. We'll use your diagnosed study persona
        to generate personalised tips using AI.
      </p>

      <form className="generate-form" onSubmit={handleGenerate} noValidate>
        {error && (
          <div className="auth-error" role="alert" aria-live="assertive">{error}</div>
        )}

        <div className="form-group">
          <label htmlFor="subject">Subject</label>
          <input
            id="subject"
            name="subject"
            type="text"
            value={form.subject}
            onChange={handleChange}
            placeholder="e.g. Database Systems, Calculus, History…"
            required
          />
        </div>

        <div className="form-group">
          <label htmlFor="education_level">Education Level</label>
          <select
            id="education_level"
            name="education_level"
            value={form.education_level}
            onChange={handleChange}
          >
            <option value="university">University</option>
            <option value="high_school">High School</option>
          </select>
        </div>

        <button
          type="submit"
          className="auth-btn"
          disabled={loading}
          aria-busy={loading}
        >
          {loading ? 'Generating…' : 'Generate Tips'}
        </button>
      </form>

      {result && (
        <section
          className="generated-result"
          aria-live="polite"
          aria-label="Generated study tips"
        >
          <h2>{result.title}</h2>
          <pre>{result.content}</pre>

          <div className="result-actions">
            {!saved ? (
              <button
                className="btn-primary"
                onClick={handleSave}
                disabled={saving}
                aria-busy={saving}
              >
                {saving ? 'Saving…' : 'Save to My Tips'}
              </button>
            ) : (
              <span style={{ color: '#059669', fontWeight: 600 }}>
                ✓ Saved to your tips
              </span>
            )}

            <button
              className="btn-secondary"
              onClick={() => { setResult(null); setSaved(false); }}
            >
              Generate Another
            </button>
          </div>

          {/* Email share */}
          <div className="share-section">
            <h3>Share these tips</h3>
            <div className="share-buttons">
              <a
                href={`mailto:?subject=${encodeURIComponent(result.title)}&body=${buildEmailBody()}`}
                className="share-btn share-btn-email"
                aria-label="Share tips by email"
              >
                Share by Email
              </a>
            </div>
          </div>
        </section>
      )}
    </main>
  );
};

export default GenerateTips;
