// pages/TipDetail.jsx
// Unique URL page for a single saved study tip (/tips/:id)

import { useEffect, useState } from 'react';
import { useParams, useNavigate, Link } from 'react-router-dom';
import { getTip, updateTip, deleteTip, toggleBookmark, submitFeedback, removeFeedback } from '../services/tipService.js';
import '../styles/tips.css';
import '../styles/auth.css';

const TipDetail = () => {
  const { id } = useParams();
  const navigate = useNavigate();

  const [tip, setTip] = useState(null);
  const [loading, setLoading] = useState(true);
  const [editing, setEditing] = useState(false);
  const [editForm, setEditForm] = useState({ title: '', content: '' });
  const [error, setError] = useState('');
  const [saving, setSaving] = useState(false);

  useEffect(() => {
    getTip(id)
      .then((res) => {
        setTip(res.data.tip);
        setEditForm({ title: res.data.tip.title, content: res.data.tip.content });
      })
      .catch(() => setError('Tip not found.'))
      .finally(() => setLoading(false));
  }, [id]);

  const handleBookmark = async () => {
    try {
      const res = await toggleBookmark(id);
      setTip((prev) => ({ ...prev, is_bookmarked: res.data.is_bookmarked }));
    } catch (err) { console.error(err); }
  };

  const handleFeedback = async (value) => {
    try {
      if (tip.feedback_value === value) {
        await removeFeedback(id);
        setTip((prev) => ({ ...prev, feedback_value: null }));
      } else {
        await submitFeedback(id, value);
        setTip((prev) => ({ ...prev, feedback_value: value }));
      }
    } catch (err) { console.error(err); }
  };

  const handleEdit = async (e) => {
    e.preventDefault();
    if (!editForm.title.trim() || !editForm.content.trim()) {
      setError('Title and content are required.'); return;
    }
    setSaving(true);
    setError('');
    try {
      const res = await updateTip(id, editForm);
      setTip(res.data.tip);
      setEditing(false);
    } catch (err) {
      setError(err.response?.data?.message || 'Update failed.');
    } finally {
      setSaving(false);
    }
  };

  const handleDelete = async () => {
    if (!window.confirm('Delete this tip? This cannot be undone.')) return;
    try {
      await deleteTip(id);
      navigate('/tips');
    } catch (err) { console.error(err); }
  };

  const buildEmailBody = () =>
    encodeURIComponent(
      `Study Tips: ${tip?.title}\n\n${tip?.content}\n\n— Generated by AcadeMe`
    );

  if (loading) return <main className="tip-detail-container"><p aria-live="polite">Loading…</p></main>;
  if (error && !tip) return <main className="tip-detail-container"><p role="alert">{error}</p></main>;

  return (
    <main className="tip-detail-container">
      <nav aria-label="Breadcrumb" style={{ marginBottom: '1rem', fontSize: '0.875rem' }}>
        <Link to="/tips" style={{ color: '#aa3bff' }}>← Back to My Tips</Link>
      </nav>

      {error && (
        <div className="auth-error" role="alert" aria-live="assertive">{error}</div>
      )}

      <header className="tip-detail-header">
        <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'flex-start', flexWrap: 'wrap', gap: '0.75rem' }}>
          <h1>{tip.title}</h1>
          <button
            className="bookmark-btn"
            onClick={handleBookmark}
            aria-label={tip.is_bookmarked ? 'Remove bookmark' : 'Bookmark this tip'}
            aria-pressed={tip.is_bookmarked}
            style={{ fontSize: '1.4rem' }}
          >
            {tip.is_bookmarked ? '🔖' : '🏷️'}
          </button>
        </div>

        <div className="tip-meta" style={{ marginTop: '0.5rem' }}>
          <span className="tag tag-persona">{tip.emoji} {tip.persona_name}</span>
          <span className="tag tag-subject">{tip.subject}</span>
          <span className="tag tag-level">
            {tip.education_level === 'university' ? 'University' : 'High School'}
          </span>
        </div>
      </header>

      {editing ? (
        <form onSubmit={handleEdit} className="generate-form" noValidate>
          <div className="form-group">
            <label htmlFor="edit-title">Title</label>
            <input
              id="edit-title"
              value={editForm.title}
              onChange={(e) => setEditForm((p) => ({ ...p, title: e.target.value }))}
              required
            />
          </div>
          <div className="form-group">
            <label htmlFor="edit-content">Content</label>
            <textarea
              id="edit-content"
              value={editForm.content}
              onChange={(e) => setEditForm((p) => ({ ...p, content: e.target.value }))}
              rows={12}
              required
              style={{ fontFamily: 'inherit' }}
            />
          </div>
          <div style={{ display: 'flex', gap: '0.75rem' }}>
            <button type="submit" className="auth-btn" disabled={saving} aria-busy={saving}>
              {saving ? 'Saving…' : 'Save Changes'}
            </button>
            <button
              type="button"
              className="btn-secondary"
              onClick={() => { setEditing(false); setError(''); }}
            >
              Cancel
            </button>
          </div>
        </form>
      ) : (
        <div className="tip-detail-content" aria-label="Tip content">
          {tip.content}
        </div>
      )}

      <div className="tip-detail-actions">
        <div className="feedback-btns" role="group" aria-label="Rate this tip">
          <button
            className={`feedback-btn${tip.feedback_value === 'up' ? ' active-up' : ''}`}
            onClick={() => handleFeedback('up')}
            aria-label="This tip resonates with me"
            aria-pressed={tip.feedback_value === 'up'}
          >
            👍 Resonates
          </button>
          <button
            className={`feedback-btn${tip.feedback_value === 'down' ? ' active-down' : ''}`}
            onClick={() => handleFeedback('down')}
            aria-label="This tip does not resonate"
            aria-pressed={tip.feedback_value === 'down'}
          >
            👎 Doesn't resonate
          </button>
        </div>

        {!editing && (
          <>
            <button className="btn-secondary" onClick={() => setEditing(true)}>
              Edit
            </button>
            <button className="btn-danger" onClick={handleDelete}>
              Delete
            </button>
          </>
        )}
      </div>

      {/* Email share */}
      <div className="share-section">
        <h3>Share these tips</h3>
        <div className="share-buttons">
          <a
            href={`mailto:?subject=${encodeURIComponent(tip.title)}&body=${buildEmailBody()}`}
            className="share-btn share-btn-email"
            aria-label="Share this tip by email"
          >
            ✉️ Share by Email
          </a>
        </div>
      </div>

      <p style={{ fontSize: '0.75rem', color: '#9ca3af', marginTop: '1.5rem' }}>
        Created {new Date(tip.created_at).toLocaleDateString()}
        {tip.updated_at !== tip.created_at &&
          ` · Updated ${new Date(tip.updated_at).toLocaleDateString()}`}
      </p>
    </main>
  );
};

export default TipDetail;
