// pages/TipDetail.jsx
// Unique URL page for a single saved study tip (/tips/:id)

import { useEffect, useState } from 'react';
import { useParams, useNavigate, Link } from 'react-router-dom';
import { getTip, deleteTip, toggleBookmark, submitFeedback, removeFeedback } from '../services/tipService.js';
import { PERSONA_AVATARS } from '../components/AvatarPicker.jsx';
import '../styles/tips.css';
import '../styles/auth.css';

const TipDetail = () => {
  const { id } = useParams();
  const navigate = useNavigate();

  const [tip, setTip] = useState(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState('');

  useEffect(() => {
    getTip(id)
      .then((res) => setTip(res.data.tip))
      .catch(() => setError('Tip not found.'))
      .finally(() => setLoading(false));
  }, [id]);

  const handleBookmark = async () => {
    try {
      const res = await toggleBookmark(id);
      setTip((prev) => ({ ...prev, is_bookmarked: res.data.is_bookmarked }));
    } catch (err) { console.error(err); }
  };

  const handleFeedback = async (value) => {
    try {
      if (tip.feedback_value === value) {
        await removeFeedback(id);
        setTip((prev) => ({ ...prev, feedback_value: null }));
      } else {
        await submitFeedback(id, value);
        setTip((prev) => ({ ...prev, feedback_value: value }));
      }
    } catch (err) { console.error(err); }
  };

  const handleDelete = async () => {
    if (!window.confirm('Delete this tip? This cannot be undone.')) return;
    try {
      await deleteTip(id);
      navigate('/tips');
    } catch (err) { console.error(err); }
  };

  const buildEmailBody = () =>
    encodeURIComponent(
      `Study Tips: ${tip?.title}\n\n${tip?.content}\n\n— Generated by AcadeMe`
    );

  if (loading) return <main className="tip-detail-container"><p aria-live="polite">Loading…</p></main>;
  if (error && !tip) return <main className="tip-detail-container"><p role="alert">{error}</p></main>;

  return (
    <main className="tip-detail-container">
      <nav aria-label="Breadcrumb" style={{ marginBottom: '1rem', fontSize: '0.875rem' }}>
        <Link to="/tips" style={{ color: '#a78bca' }}>← Back to My Tips</Link>
      </nav>

      {error && (
        <div className="auth-error" role="alert" aria-live="assertive">{error}</div>
      )}

      <header className="tip-detail-header">
        <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'flex-start', flexWrap: 'wrap', gap: '0.75rem' }}>
          <h1>{tip.title}</h1>
          <button
            className={`bookmark-btn${tip.is_bookmarked ? ' bookmarked' : ''}`}
            onClick={handleBookmark}
            aria-label={tip.is_bookmarked ? 'Remove bookmark' : 'Bookmark this tip'}
            aria-pressed={tip.is_bookmarked}
          >
            {tip.is_bookmarked ? (
              <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" viewBox="0 0 24 24" fill="currentColor" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" aria-hidden="true"><path d="m19 21-7-4-7 4V5a2 2 0 0 1 2-2h10a2 2 0 0 1 2 2v16z"/></svg>
            ) : (
              <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" aria-hidden="true"><path d="m19 21-7-4-7 4V5a2 2 0 0 1 2-2h10a2 2 0 0 1 2 2v16z"/></svg>
            )}
          </button>
        </div>

        <div className="tip-meta" style={{ marginTop: '0.5rem' }}>
          <span className="tag tag-persona">
            {(() => {
              const av = PERSONA_AVATARS.find((a) => a.key === tip.persona_key);
              return av?.image ? (
                <img src={av.image} alt="" aria-hidden="true" style={{ width: 16, height: 16, borderRadius: 3, objectFit: 'cover', marginRight: 4, verticalAlign: 'middle' }} />
              ) : null;
            })()}
            {tip.persona_name}
          </span>
          <span className="tag tag-subject">{tip.subject}</span>
          <span className="tag tag-level">
            {tip.education_level === 'university' ? 'University' : 'High School'}
          </span>
        </div>
      </header>

      <div className="tip-detail-content" aria-label="Tip content">
        {tip.content}
      </div>

      <div className="tip-detail-actions">
        <div className="feedback-btns" role="group" aria-label="Rate this tip">
          <button
            className={`feedback-btn${tip.feedback_value === 'up' ? ' active-up' : ''}`}
            onClick={() => handleFeedback('up')}
            aria-label="This tip resonates with me"
            aria-pressed={tip.feedback_value === 'up'}
            title="Resonates"
          >
            <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" aria-hidden="true"><path d="M7 10v12"/><path d="M15 5.88 14 10h5.83a2 2 0 0 1 1.92 2.56l-2.33 8A2 2 0 0 1 17.5 22H4a2 2 0 0 1-2-2v-8a2 2 0 0 1 2-2h2.76a2 2 0 0 0 1.79-1.11L12 2a3.13 3.13 0 0 1 3 3.88Z"/></svg>
          </button>
          <button
            className={`feedback-btn${tip.feedback_value === 'down' ? ' active-down' : ''}`}
            onClick={() => handleFeedback('down')}
            aria-label="This tip does not resonate"
            aria-pressed={tip.feedback_value === 'down'}
            title="Doesn't resonate"
          >
            <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" aria-hidden="true"><path d="M17 14V2"/><path d="M9 18.12 10 14H4.17a2 2 0 0 1-1.92-2.56l2.33-8A2 2 0 0 1 6.5 2H20a2 2 0 0 1 2 2v8a2 2 0 0 1-2 2h-2.76a2 2 0 0 0-1.79 1.11L12 22a3.13 3.13 0 0 1-3-3.88Z"/></svg>
          </button>
        </div>

        <button className="btn-danger" onClick={handleDelete}>
          Delete
        </button>
      </div>

      <div className="share-section">
        <h3>Share these tips</h3>
        <div className="share-buttons">
          <a
            href={`mailto:?subject=${encodeURIComponent(tip.title)}&body=${buildEmailBody()}`}
            className="share-btn share-btn-email"
            aria-label="Share this tip by email"
          >
            Share by Email
          </a>
        </div>
      </div>

      <p style={{ fontSize: '0.75rem', color: '#9ca3af', marginTop: '1.5rem' }}>
        Created {new Date(tip.created_at).toLocaleDateString()}
      </p>
    </main>
  );
};

export default TipDetail;
