// pages/TipDetail.jsx
// Unique URL page for a single saved study tip (/tips/:id)

import { useEffect, useState } from 'react';
import { useParams, useNavigate, Link } from 'react-router-dom';
import { getTip, deleteTip, toggleBookmark, submitFeedback, removeFeedback } from '../services/tipService.js';
import { PERSONA_AVATARS } from '../components/AvatarPicker.jsx';
import '../styles/tips.css';

const BookmarkIcon = ({ filled }) => filled ? (
  <svg xmlns="http://www.w3.org/2000/svg" width="18" height="18" viewBox="0 0 24 24" fill="currentColor" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" aria-hidden="true"><path d="m19 21-7-4-7 4V5a2 2 0 0 1 2-2h10a2 2 0 0 1 2 2v16z"/></svg>
) : (
  <svg xmlns="http://www.w3.org/2000/svg" width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" aria-hidden="true"><path d="m19 21-7-4-7 4V5a2 2 0 0 1 2-2h10a2 2 0 0 1 2 2v16z"/></svg>
);

const ThumbUp = () => (
  <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" aria-hidden="true"><path d="M7 10v12"/><path d="M15 5.88 14 10h5.83a2 2 0 0 1 1.92 2.56l-2.33 8A2 2 0 0 1 17.5 22H4a2 2 0 0 1-2-2v-8a2 2 0 0 1 2-2h2.76a2 2 0 0 0 1.79-1.11L12 2a3.13 3.13 0 0 1 3 3.88Z"/></svg>
);

const ThumbDown = () => (
  <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" aria-hidden="true"><path d="M17 14V2"/><path d="M9 18.12 10 14H4.17a2 2 0 0 1-1.92-2.56l2.33-8A2 2 0 0 1 6.5 2H20a2 2 0 0 1 2 2v8a2 2 0 0 1-2 2h-2.76a2 2 0 0 0-1.79 1.11L12 22a3.13 3.13 0 0 1-3-3.88Z"/></svg>
);

const TipDetail = () => {
  const { id } = useParams();
  const navigate = useNavigate();

  const [tip, setTip] = useState(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState('');

  useEffect(() => {
    getTip(id)
      .then((res) => setTip(res.data.tip))
      .catch(() => setError('Tip not found.'))
      .finally(() => setLoading(false));
  }, [id]);

  const handleBookmark = async () => {
    try {
      const res = await toggleBookmark(id);
      setTip((prev) => ({ ...prev, is_bookmarked: res.data.is_bookmarked }));
    } catch (err) { console.error(err); }
  };

  const handleFeedback = async (value) => {
    try {
      if (tip.feedback_value === value) {
        await removeFeedback(id);
        setTip((prev) => ({ ...prev, feedback_value: null }));
      } else {
        await submitFeedback(id, value);
        setTip((prev) => ({ ...prev, feedback_value: value }));
      }
    } catch (err) { console.error(err); }
  };

  const handleDelete = async () => {
    if (!window.confirm('Delete this tip? This cannot be undone.')) return;
    try {
      await deleteTip(id);
      navigate('/tips');
    } catch (err) { console.error(err); }
  };

  const buildEmailBody = () =>
    encodeURIComponent(`Study Tips: ${tip?.title}\n\n${tip?.content}\n\n— Generated by AcadeMe`);

  if (loading) return (
    <main className="tip-detail-page">
      <div className="tip-detail-card"><p aria-live="polite">Loading…</p></div>
    </main>
  );
  if (error && !tip) return (
    <main className="tip-detail-page">
      <div className="tip-detail-card"><p role="alert">{error}</p></div>
    </main>
  );

  const personaAvatar = PERSONA_AVATARS.find((a) => a.key === tip.persona_key);

  return (
    <main className="tip-detail-page">

      <nav className="tip-detail-breadcrumb" aria-label="Breadcrumb">
        <Link to="/tips">← Back to My Tips</Link>
      </nav>

      <article className="tip-detail-card">

        {/* HEADER */}
        <header className="tip-detail-card-header">
          <div className="tip-detail-title-row">
            <h1 className="tip-detail-title">{tip.title}</h1>
            <button
              className={`bookmark-btn${tip.is_bookmarked ? ' bookmarked' : ''}`}
              onClick={handleBookmark}
              aria-label={tip.is_bookmarked ? 'Remove bookmark' : 'Bookmark this tip'}
              aria-pressed={tip.is_bookmarked}
              title={tip.is_bookmarked ? 'Remove bookmark' : 'Bookmark'}
            >
              <BookmarkIcon filled={tip.is_bookmarked} />
            </button>
          </div>

          <div className="tip-meta">
            {personaAvatar?.image && (
              <img src={personaAvatar.image} alt="" aria-hidden="true" className="tip-meta-avatar" />
            )}
            <span className="tag tag-persona">{tip.persona_name}</span>
            <span className="tag tag-subject">{tip.subject}</span>
            <span className="tag tag-level">
              {tip.education_level === 'university' ? 'University' : 'High School'}
            </span>
          </div>
        </header>

        {/* TIPS CONTENT */}
        <div className="tip-detail-body" aria-label="Tip content">
          {tip.content
            .split(/\n/)
            .filter((line) => /^\d+\./.test(line.trim()))
            .map((line, i) => (
              <div key={i} className="tip-detail-item">
                <span className="tip-detail-num">{i + 1}</span>
                <p>{line.replace(/^\d+\.\s*/, '')}</p>
              </div>
            ))}
          {/* Fallback if content isn't numbered list format */}
          {!tip.content.match(/^\d+\./m) && (
            <p className="tip-detail-raw">{tip.content}</p>
          )}
        </div>

        {/* FOOTER ACTIONS */}
        <footer className="tip-detail-card-footer">
          <div className="tip-detail-left">
            <div className="feedback-btns" role="group" aria-label="Rate this tip">
              <button
                className={`feedback-btn${tip.feedback_value === 'up' ? ' active-up' : ''}`}
                onClick={() => handleFeedback('up')}
                aria-label="This tip resonates with me"
                aria-pressed={tip.feedback_value === 'up'}
                title="Resonates"
              >
                <ThumbUp />
              </button>
              <button
                className={`feedback-btn${tip.feedback_value === 'down' ? ' active-down' : ''}`}
                onClick={() => handleFeedback('down')}
                aria-label="This tip does not resonate"
                aria-pressed={tip.feedback_value === 'down'}
                title="Doesn't resonate"
              >
                <ThumbDown />
              </button>
            </div>
            <span className="tip-detail-date">
              {new Date(tip.created_at).toLocaleDateString()}
            </span>
          </div>

          <div className="tip-detail-right">
            <a
              href={`mailto:?subject=${encodeURIComponent(tip.title)}&body=${buildEmailBody()}`}
              className="btn-secondary"
              aria-label="Share this tip by email"
            >
              Share by Email
            </a>
            <button className="btn-danger" onClick={handleDelete}>
              Delete
            </button>
          </div>
        </footer>

      </article>
    </main>
  );
};

export default TipDetail;
